"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Check, LockKeyhole } from "lucide-react";
import { useStore } from "@/components/store-provider";
import { CartSummary } from "@/components/cart-summary";
import { calculateEstimatedTax, calculateShipping, calculateSubtotal } from "@/lib/pricing";

export default function CheckoutPage() { const { cart, clearCart } = useStore(); const router = useRouter(); const [error,setError] = useState(""); const [shipping,setShipping] = useState<"Standard" | "Express">("Standard"); if(!cart.length) return <section className="empty-page page"><LockKeyhole size={35}/><p className="eyebrow">Checkout</p><h1>Your bag is ready when you are.</h1><p>Add a piece to continue to the demo checkout.</p><Link href="/shop" className="button">Explore products</Link></section>;
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const fd = new FormData(e.currentTarget); const fields = ["email","name","address","city","postal","country","phone","cardholder","card","expiry","cvc"]; if(fields.some(key=>!String(fd.get(key)||"").trim())) return setError("Please complete all required checkout details."); if(!String(fd.get("email")).includes("@")) return setError("Enter a valid email address."); const subtotal=calculateSubtotal(cart.map(i=>({price:i.product.price,quantity:i.quantity}))); const shippingCost=shipping === "Express" ? 18 : calculateShipping(subtotal); const tax=calculateEstimatedTax(subtotal); const order={id:`NORDLY-${Math.floor(10000+Math.random()*89999)}`,firstName:String(fd.get("name")).split(" ")[0],items:cart,total:subtotal+shippingCost+tax,subtotal,shipping:shippingCost,tax,method:shipping}; localStorage.setItem("nordly-last-order",JSON.stringify(order)); clearCart(); router.push("/order-confirmation"); };
  return <section className="checkout-page page"><div className="checkout-top"><Link className="wordmark" href="/">NORDLY</Link><span><LockKeyhole size={14}/> Secure demo checkout</span></div><div className="checkout-steps"><b><i>1</i> Information</b><b><i>2</i> Shipping</b><b><i>3</i> Payment</b><b><i>4</i> Review</b></div><div className="checkout-layout"><form onSubmit={submit} noValidate><div className="checkout-section"><h1>Information</h1><label>Email<input name="email" type="email" placeholder="you@example.com"/></label><h2>Shipping address</h2><div className="form-grid"><label>Full name<input name="name" placeholder="Emma Johnson"/></label><label>Phone<input name="phone" type="tel" placeholder="(555) 123-4567"/></label></div><label>Address<input name="address" placeholder="123 Scandinavian Way"/></label><label>Apartment, suite, etc. <span>optional</span><input name="apartment" placeholder="Apartment 4B"/></label><div className="form-grid three"><label>City<input name="city" placeholder="Copenhagen"/></label><label>State / Province<input name="state" placeholder="Capital Region"/></label><label>Postal code<input name="postal" placeholder="2100"/></label></div><label>Country<select name="country" defaultValue=""><option value="" disabled>Select country</option><option>United States</option><option>Denmark</option><option>United Kingdom</option><option>Canada</option></select></label></div><div className="checkout-section"><h2>Shipping method</h2><label className={`radio-card ${shipping==="Standard"?"selected":""}`}><input type="radio" checked={shipping==="Standard"} onChange={()=>setShipping("Standard")}/> <span><b>Standard</b><small>3–5 business days</small></span><b>Complimentary</b></label><label className={`radio-card ${shipping==="Express"?"selected":""}`}><input type="radio" checked={shipping==="Express"} onChange={()=>setShipping("Express")}/> <span><b>Express</b><small>1–2 business days</small></span><b>$18.00</b></label></div><div className="checkout-section"><h2>Payment</h2><p className="demo-note">Portfolio checkout — no real payment is processed or stored.</p><label className="radio-card selected"><input type="radio" defaultChecked/> <span><b>Credit / Debit Card</b><small>Demo card details only</small></span><Check size={18}/></label><label>Cardholder name<input name="cardholder" placeholder="Emma Johnson"/></label><label>Card number<input name="card" inputMode="numeric" placeholder="4242 4242 4242 4242"/></label><div className="form-grid"><label>Expiry<input name="expiry" placeholder="MM / YY"/></label><label>CVC<input name="cvc" placeholder="123"/></label></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button place-order" type="submit">Place demo order</button></form><CartSummary checkout shippingMethod={shipping}/></div></section>; }
