"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { formatCurrency } from "@/lib/pricing";
import type { CartItem } from "@/components/store-provider";
type Order = {id:string;firstName:string;items:CartItem[];total:number;subtotal:number;shipping:number;tax:number};
export default function OrderConfirmation() { const [order,setOrder] = useState<Order|null>(null); useEffect(()=>{const data=localStorage.getItem("nordly-last-order");if(data)setOrder(JSON.parse(data));},[]); if(!order) return <section className="empty-page page"><p className="eyebrow">NORDLY demo</p><h1>There’s no demo order to show yet.</h1><Link className="button" href="/shop">Explore products</Link></section>; return <section className="confirmation page"><CheckCircle2 size={46}/><p className="eyebrow">Order created</p><h1>Thank you, {order.firstName}.</h1><p>Your demo order has been created. No payment, email, or real shipment has been processed.</p><div className="confirmation-meta"><span><small>Order number</small><b>{order.id}</b></span><span><small>Estimated delivery</small><b>3–5 demo business days</b></span><span><small>Order total</small><b>{formatCurrency(order.total)}</b></span></div><div className="confirmation-summary"><h2>Order summary</h2>{order.items.map(item=><div key={item.product.id} className="confirmation-item"><Image src={item.product.image} alt={item.product.name} fill style={{objectFit:"cover"}}/><span><b>{item.product.name}</b><small>Quantity {item.quantity}</small></span><b>{formatCurrency(item.product.price*item.quantity)}</b></div>)}<div className="order-totals"><span>Subtotal <b>{formatCurrency(order.subtotal)}</b></span><span>Shipping <b>{order.shipping?formatCurrency(order.shipping):"Complimentary"}</b></span><span>Estimated tax <b>{formatCurrency(order.tax)}</b></span><span>Total <b>{formatCurrency(order.total)}</b></span></div></div><div className="confirmation-buttons"><Link href="/shop" className="button">Continue shopping</Link><a href="#order-summary" className="button button-light">View order summary</a></div><small className="disclosure">Portfolio demonstration — no real order or payment was created.</small></section>; }
