"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, ChevronRight, CreditCard, Leaf, RotateCcw, Truck } from "lucide-react";
import { categories, products } from "@/data/products";
import { ProductCard, ProductGrid } from "@/components/product-card";
import { useState } from "react";

export default function Home() {
  const [email, setEmail] = useState(""); const [joined, setJoined] = useState(false);
  return <>
    <section className="hero page"><Image src="/images/nordly-interiors.png" alt="Serene Scandinavian living room with natural materials" fill loading="eager" sizes="100vw" style={{ objectFit: "cover", objectPosition: "16% 55%" }}/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">New season / 2026</p><h1>Live beautifully.<br/>Shop consciously.</h1><p>Thoughtfully selected furniture, lighting, textiles, and objects for calm, functional spaces.</p><div className="hero-buttons"><Link className="button" href="/new-arrivals">Shop new arrivals</Link><Link className="button button-light" href="/collections">Explore collections</Link></div></div><div className="hero-note"><span>01</span> A quieter way to live</div></section>
    <section className="service-strip"><div className="page">{[[Truck,"Complimentary Shipping","On orders over $100"],[RotateCcw,"Easy Returns","30-day return window"],[CreditCard,"Secure Checkout","Protected demo checkout"],[Leaf,"Thoughtful Selection","Curated for everyday living"]].map(([Icon,title,text],i)=>{const I=Icon as typeof Truck;return <div className="service" key={String(title)}><I size={20}/><span><strong>{String(title)}</strong><small>{String(text)}</small></span></div>})}</div></section>
    <section className="category-section page"><div className="section-heading"><div><p className="eyebrow">Find your room</p><h2>Shop by category</h2></div><Link href="/shop" className="text-link">Shop all <span>→</span></Link></div><div className="category-grid">{categories.map((cat, index)=><Link href={`/category/${cat.slug}`} className={`category-card category-card-${index}`} key={cat.slug}><Image src={cat.image} alt={`${cat.name} collection`} fill sizes="(max-width: 700px) 50vw, 17vw" style={{objectFit:"cover"}}/><span><strong>{cat.name}</strong><ChevronRight size={18}/></span></Link>)}</div></section>
    <ProductGrid title="New arrivals" viewAllHref="/new-arrivals" items={products.filter(p=>p.newArrival).slice(0,4)}/>
    <section className="editorial page"><div className="editorial-image"><Image src="/images/nordly-interiors.png" alt="Warmly lit table lamp and neutral interior" fill sizes="(max-width: 900px) 100vw, 50vw" style={{objectFit:"cover",objectPosition:"51% 54%"}}/></div><div className="editorial-copy"><p className="eyebrow">The NORDLY edit</p><h2>Objects that make everyday spaces feel considered.</h2><p>Explore pieces selected for texture, function, and quiet character.</p><Link href="/collections/soft-neutrals" className="text-link">Explore the collection <ArrowUpRight size={15}/></Link></div></section>
    <ProductGrid title="Best sellers" viewAllHref="/best-sellers" items={products.filter(p=>p.bestSeller).slice(0,4)}/>
    <section className="room-feature"><div className="page room-layout"><div className="room-copy"><p className="eyebrow">Featured room / soft neutrals</p><h2>Room to exhale.</h2><p>Familiar materials, softened edges, and a palette designed to linger beyond the season.</p><Link href="/collections/soft-neutrals" className="button">Explore soft neutrals</Link></div><div className="room-scene"><Image src="/images/nordly-interiors.png" alt="A soft neutral Scandinavian lounge" fill sizes="(max-width: 900px) 100vw, 56vw" style={{objectFit:"cover",objectPosition:"15% 58%"}}/><div className="room-callout callout-one">Arne Lounge Chair <b>$895</b></div><div className="room-callout callout-two">Copenhagen Lamp <b>$129</b></div></div></div></section>
    <section className="newsletter"><div className="page"><div><p className="eyebrow">A note from NORDLY</p><h2>Join the NORDLY Journal</h2><p>New collections, thoughtful interiors, and occasional offers.</p></div>{joined?<div className="newsletter-success"><CheckCircle2/> Thanks for joining NORDLY.</div>:<form onSubmit={e=>{e.preventDefault();if(email) setJoined(true)}}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" required/><button className="button" type="submit">Subscribe</button></form>}</div></section>
  </>;
}
