"use client";

import { useMemo, useState } from "react";
import { ChevronDown, SlidersHorizontal, X } from "lucide-react";
import { Product, products } from "@/data/products";
import { ProductCard } from "./product-card";

export type CatalogInitial = { title?: string; eyebrow?: string; description?: string; items?: Product[]; query?: string };
const colorOptions = ["Natural", "Warm White", "Sage"];
const materialOptions = ["Oak", "Linen", "Wool", "Ceramic", "Glass", "Rattan", "Metal"];

export function Catalog({ title = "All Products", eyebrow = "NORDLY collection", description, items = products, query }: CatalogInitial) {
  const [category, setCategory] = useState("All"); const [material, setMaterial] = useState(""); const [availability, setAvailability] = useState(""); const [sort, setSort] = useState("featured"); const [maxPrice, setMaxPrice] = useState(1000); const [drawer, setDrawer] = useState(false);
  const visible = useMemo(() => items.filter(p => (category === "All" || p.category === category) && (!material || p.materials.includes(material)) && (!availability || p.stockStatus === availability) && p.price <= maxPrice).sort((a,b) => sort === "low" ? a.price-b.price : sort === "high" ? b.price-a.price : sort === "rating" ? b.rating-a.rating : sort === "new" ? Number(!!b.newArrival)-Number(!!a.newArrival) : Number(!!b.featured)-Number(!!a.featured)), [items, category, material, availability, sort, maxPrice]);
  const filters = <aside className="filters"><div className="filter-head"><strong>Filters</strong><button onClick={() => {setCategory("All");setMaterial("");setAvailability("");setMaxPrice(1000)}}>Clear all</button><button className="mobile-only icon" onClick={() => setDrawer(false)}><X size={18}/></button></div><fieldset><legend>Category</legend>{["All", "Furniture", "Lighting", "Textiles", "Home Decor", "Tableware", "Accessories"].map(v=><label key={v}><input type="radio" checked={category===v} onChange={()=>setCategory(v)}/>{v}</label>)}</fieldset><fieldset><legend>Price</legend><input aria-label="Maximum price" type="range" min="30" max="1000" step="10" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)}/><span>Up to ${maxPrice}</span></fieldset><fieldset><legend>Material</legend>{materialOptions.map(v=><label key={v}><input type="radio" checked={material===v} onChange={()=>setMaterial(material===v?"":v)}/>{v}</label>)}</fieldset><fieldset><legend>Color</legend><div className="color-row">{colorOptions.map((c,i)=><button key={c} aria-label={c} className={`swatch swatch-${i}`} />)}</div></fieldset><fieldset><legend>Availability</legend>{["In stock", "Low stock"].map(v=><label key={v}><input type="radio" checked={availability===v} onChange={()=>setAvailability(availability===v?"":v)}/>{v}</label>)}</fieldset></aside>;
  return <section className="catalog-page page"><div className="catalog-intro"><p className="eyebrow">{query ? "Search results" : eyebrow}</p><h1>{query ? `Results for “${query}”` : title}</h1>{description && <p>{description}</p>}</div><div className="catalog-tools"><span>Showing {visible.length} {visible.length === 1 ? "piece" : "pieces"}</span><button className="filter-trigger mobile-only" onClick={()=>setDrawer(true)}><SlidersHorizontal size={16}/> Filters</button><label className="sort">Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="new">Newest</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="rating">Customer Rating</option></select><ChevronDown size={14}/></label></div><div className="catalog-body">{filters}<div className="catalog-grid">{visible.length ? visible.map((p,index)=><ProductCard product={p} priority={index < 2} key={p.id}/>) : <div className="empty-catalog"><h2>No pieces found</h2><p>Try clearing a filter or choosing a different search.</p><button onClick={()=>{setCategory("All");setMaterial("");setAvailability("");setMaxPrice(1000)}} className="button">Clear filters</button></div>}</div></div>{drawer && <div className="filter-drawer" role="dialog" aria-label="Product filters">{filters}</div>}</section>;
}
